project_name: gnopls

before:
  hooks:
    - go mod tidy

builds:
  - id: gnopls
    binary: gnopls
    goos:
      - linux
      - darwin
      - js
    goarch:
      - amd64
      - arm64
      - wasm
    ldflags:
      - -s -w -X 'github.com/gnolang/gnopls/internal/version.Version={{.Tag}}'

changelog:
  sort: asc

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append